require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'musicStrongPlayer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  pod 'RNReactNativeGetMusicFiles', :path => '../node_modules/react-native-get-music-files'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'

  target 'musicStrongPlayerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'musicStrongPlayer-tvOS' do
  # Pods for musicStrongPlayer-tvOS

  target 'musicStrongPlayer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
